# Generated by Django 4.2.16 on 2025-01-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image_basket"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
